title: Charles Langlois
subtitle: Curriculum Vitae
url: https://cv.charleslanglois.dev
remote_theme: pages-themes/hacker@v0.2.0
markdown: kramdown
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jemoji
