title: Charles Langlois
subtitle: Curriculum Vitae
domain: cv.charleslanglois.dev
url: https://cv.charleslanglois.dev
theme: jekyll-theme-hacker
markdown: kramdown
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jemoji
